# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"autoblock": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://asvcode.github.io/auto_block/"

git_url = "https://github.com/asvcode/auto_block/tree/master/"

def custom_doc_links(name): return None
